spring.datasource.url=jdbc:postgresql://localhost:5432/coffee_orders
spring.datasource.username=postgres
spring.datasource.password=secret
logging.level.org.springframework.security=DEBUG
seed.employee.password=readytograduate
jwt.secret.value=your-secret-key-that-is-long-enough-for-testing-purposes-256bits